// Client-safe catalog of the Green Key Consumption framework's numeric
// datapoints (framework d990e70e-1622-4289-bbac-7d11d4e7e8a3), taken from the
// official BeCause group report. 61 numeric datapoints across 5 groups. The two
// non-numeric items (25. Calculation method, 26. If other) are omitted since the
// importer sends numbers.
//
// `key` is a stable slug used in the saved field_map + the import form.
// `num` is the datapoint's number on the report (for cross-checking).
// The datapoint's BeCause GUID + unit GUID are NOT hardcoded here — they're
// discovered from the API and stored per-key in because_config.field_map.

export interface DpDef { key: string; num: number; label: string }
export interface DpGroup { id: string; title: string; points: DpDef[] }

export const DP_GROUPS: DpGroup[] = [
  {
    id: 'business', title: 'Business Metrics',
    points: [
      { key: 'employees', num: 1, label: 'Total number of employees (yearly average)' },
      { key: 'suppliers', num: 2, label: 'Number of suppliers' },
      { key: 'occupied_rooms', num: 3, label: 'Total number of occupied rooms in reporting period' },
      { key: 'bednights', num: 4, label: 'Number of bednights' },
      { key: 'floor_area', num: 5, label: 'Gross internal floor area' },
    ],
  },
  {
    id: 'energy', title: 'Energy Consumption',
    points: [
      { key: 'energy_total', num: 6, label: 'Total energy consumption' },
      { key: 'electricity', num: 7, label: 'Purchased electricity' },
      { key: 'renewable_electricity', num: 8, label: 'Purchased renewable electricity' },
      { key: 'purchased_heating_cooling', num: 9, label: 'Purchased heating or cooling' },
      { key: 'district_heating', num: 10, label: 'District heating from a local utility' },
      { key: 'district_cooling', num: 11, label: 'District cooling from a local utility' },
      { key: 'cng', num: 12, label: 'Compressed Natural Gas (CNG)' },
      { key: 'natural_gas', num: 13, label: 'Natural gas' },
      { key: 'lpg_stationary', num: 14, label: 'Liquefied petroleum gas (LPG) - stationary use' },
      { key: 'diesel_stationary', num: 15, label: 'Diesel (stationary use)' },
      { key: 'diesel_mobile', num: 16, label: 'Diesel for mobile or vehicular use' },
      { key: 'petrol_mobile', num: 17, label: 'Petrol/Gasoline for mobile or vehicular use' },
      { key: 'fuel_oil', num: 18, label: 'Fuel Oil' },
      { key: 'biofuels', num: 19, label: 'Biofuels (wood logs, chips & pellets)' },
      { key: 'onsite_generation', num: 20, label: 'Onsite electricity generation - Renewables & alternative sources' },
      { key: 'onsite_renewable', num: 21, label: 'Consumption of onsite renewable energy sources' },
      { key: 'onsite_solar', num: 22, label: 'Consumption of onsite electricity generated by solar power' },
      { key: 'onsite_wind', num: 23, label: 'Consumption of onsite electricity generated by wind power' },
      { key: 'onsite_hydro', num: 24, label: 'Consumption of onsite electricity generated by hydropower' },
    ],
  },
  {
    id: 'ghg', title: 'GHG Emissions',
    points: [
      { key: 'total_emissions', num: 27, label: 'Total emissions' },
      { key: 'cf_guestrooms', num: 28, label: 'Total Guestrooms Carbon Footprint' },
      { key: 'cf_meetings', num: 29, label: 'Total Meetings Carbon Footprint' },
      { key: 'cf_per_room', num: 30, label: 'Carbon Footprint per occupied room on a daily basis' },
      { key: 'cf_per_meeting_area', num: 31, label: 'Carbon Footprint per area of a meeting space (1 sqm/sqft) hourly' },
      { key: 'cf_per_sqm', num: 32, label: 'Carbon Footprint per sqm/sqft on an annual basis' },
      { key: 'scope1', num: 33, label: 'Scope 1' },
      { key: 'scope2', num: 34, label: 'Scope 2' },
      { key: 'scope3', num: 35, label: 'Scope 3' },
    ],
  },
  {
    id: 'waste', title: 'Waste Production',
    points: [
      { key: 'waste', num: 36, label: 'Total amount of waste' },
      { key: 'cardboard_w', num: 37, label: 'Cardboard (weight)' },
      { key: 'cardboard_v', num: 38, label: 'Cardboard (volume)' },
      { key: 'paper_w', num: 39, label: 'Paper (weight)' },
      { key: 'paper_v', num: 40, label: 'Paper (volume)' },
      { key: 'paper_cardboard_w', num: 41, label: 'Paper & Cardboard (weight)' },
      { key: 'paper_cardboard_v', num: 42, label: 'Paper & Cardboard (volume)' },
      { key: 'glass_w', num: 43, label: 'Glass (weight)' },
      { key: 'glass_v', num: 44, label: 'Glass (volume)' },
      { key: 'food_w', num: 45, label: 'Food waste (weight)' },
      { key: 'food_v', num: 46, label: 'Food waste (volume)' },
      { key: 'plastics_w', num: 47, label: 'Plastics (weight)' },
      { key: 'plastics_v', num: 48, label: 'Plastics (volume)' },
      { key: 'metals_w', num: 49, label: 'Metals (weight)' },
      { key: 'metals_v', num: 50, label: 'Metals (volume)' },
      { key: 'oil_w', num: 51, label: 'Edible oil and fat (weight)' },
      { key: 'oil_v', num: 52, label: 'Edible oil and fat (volume)' },
      { key: 'mixed_w', num: 53, label: 'Mixed municipal waste (weight)' },
      { key: 'mixed_v', num: 54, label: 'Mixed municipal waste (volume)' },
      { key: 'biodegradable_w', num: 55, label: 'Biodegradable waste (weight)' },
      { key: 'biodegradable_v', num: 56, label: 'Biodegradable waste (volume)' },
      { key: 'hazardous_w', num: 57, label: 'Hazardous waste (weight)' },
      { key: 'ewaste_w', num: 58, label: 'Separated electronic waste (weight)' },
      { key: 'batteries_w', num: 59, label: 'Separated batteries (weight)' },
    ],
  },
  {
    id: 'water', title: 'Water Consumption',
    points: [
      { key: 'water', num: 60, label: 'Total water consumption' },
      { key: 'water_surface', num: 61, label: 'Inputs from surface water' },
      { key: 'water_ground', num: 62, label: 'Inputs from groundwater - medium quality (category 2)' },
      { key: 'water_thirdparty', num: 63, label: 'Inputs from third party suppliers' },
    ],
  },
]

// Flat list of every datapoint key, in report order.
export const DP_ALL: DpDef[] = DP_GROUPS.flatMap((g) => g.points)
export const DP_KEYS: string[] = DP_ALL.map((p) => p.key)
